server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /
app:
  aws:
    region: eu-central-1
    accessKey: foo
    secretKey: bar
    endpoint: http://localhost:4566
    bucket: some-bucket