services:
  "file-server":
    build:
      context: ./FileServer
    container_name: "file-server"
    environment:
      LOCALSTACK_URL: "http://localstack:4566"
      S3_BUCKET: "some-bucket"
      SPRING_PROFILES_ACTIVE: compose
    labels:
    - traefik.enable=true
    - "traefik.http.routers.file-server.rule=Host(`file-server.localhost`)"
    - "traefik.http.routers.file-server.entrypoints=web"
    - "traefik.http.services.file-server.loadbalancer.server.port=8000"
    ports:
    - "8000:8000"
    - "8010:8010"
    volumes:
    - "./FileServer/target/server.jar:/opt/app.jar:ro"
  localstack:
    container_name: localstack
    environment:
      DEBUG: '1'
      DEFAULT_REGION: "eu-central-1"
      S3_BUCKET: "some-bucket"
      SERVICES: s3
    image: "localstack/localstack:0.13.2"
    labels:
    - traefik.enable=true
    - "traefik.http.routers.localstack.rule=Host(`localstack.localhost`)"
    - traefik.http.routers.localstack.entrypoints=web
    - traefik.http.services.localstack.loadbalancer.server.port=4566
    networks:
      default:
        aliases:
        - "some-bucket.localstack"
    ports:
    - "4566:4566"
    restart: "unless-stopped"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./createS3.sh:/docker-entrypoint-initaws.d/createS3.sh"
  "reactive-file-client":
    build:
      context: ./ReactiveClient
    container_name: "reactive-client"
    environment:
      SERVER_URL: "http://reactive-file-server:9000"
      SPRING_PROFILES_ACTIVE: compose
    labels:
    - traefik.enable=true
    - "traefik.http.routers.reactive-client.rule=Host(`reactive-client.localhost`)"
    - "traefik.http.routers.reactive-client.entrypoints=web"
    - "traefik.http.services.reactive-client.loadbalancer.server.port=9001"
    ports:
    - "9001:9001"
    - "9011:9011"
    volumes:
    - "./ReactiveClient/target/client.jar:/opt/app.jar:ro"
  "reactive-file-server":
    build:
      context: ./ReactiveFileServer
    container_name: "reactive-file-server"
    environment:
      LOCALSTACK_URL: "http://localstack:4566"
      S3_BUCKET: "some-bucket"
      SPRING_PROFILES_ACTIVE: compose
    labels:
    - traefik.enable=true
    - "traefik.http.routers.reactive-file-server.rule=Host(`reactive-file-server.localhost`)"
    - "traefik.http.routers.reactive-file-server.entrypoints=web"
    - "traefik.http.services.reactive-file-server.loadbalancer.server.port=9000"
    ports:
    - "9000:9000"
    - "9010:9010"
    volumes:
    - "./ReactiveFileServer/target/server.jar:/opt/app.jar:ro"
  traefik:
    command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--entrypoints.web.address=:80"
    container_name: traefik
    image: "traefik:v2.5.6"
    ports:
    - "80:80"
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
version: '3.9'
