openapi: 3.0.3
info:
  title: FileApi
  description: FileApi
  version: 1.0.0
servers:
  - url: 'http://localhost:9000'
paths:
  /download:
    get:
      tags:
        - File
      summary: returns a file as bytearray
      parameters:
        - in: query
          name: key
          schema:
            type: string
          required: true
      responses:
        200:
          description: A file
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  type: string
                  format: byte
  /information:
    get:
      tags:
        - File
      summary: returns information to all files for a given folder
      parameters:
        - in: query
          name: folder
          schema:
            type: string
          required: true
      responses:
        200:
          description: returns an array with all file informations
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FileInformation'
  /files:
    get:
      tags:
        - FileMem
      summary: returns Information and Content for a given folder (High memory usage)
      parameters:
        - in: query
          name: folder
          schema:
            type: string
          required: true
      responses:
        200:
          description: returns an array with all files from folder
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FileContent'
components:
  schemas:
    FileInformation:
      properties:
        name:
          type: string
        size:
          type: integer
          format: int64
        path:
          type: string
          format: uri
    FileContent:
      properties:
        name:
          type: string
        size:
          type: integer
          format: int64
        path:
          type: string
          format: uri
        content:
          type: string
          format: byte